version: '{build}'
skip_tags: true
environment:
  matrix:
  - GENERATOR: Visual Studio 12 Win64
    DEPS_PATH: deps64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-msvc.exe"
  - rust-beta-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
build_script:
- scripts\vcvarsx86_amd64.bat
- scripts\win64_build_debug.cmd
