[package]
name = "viewdock"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.4"
syntex = "0.32.0"

[dependencies]
minifb = "0.7.1"
serde = "0.7.4"
serde_json = "0.7.0"

